server:
  port: ${SERVER_PORT:80}
  netty:
    idle-timeout: ${NETTY_IDLE_TIMEOUT:PT60S}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: penalties-search
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB_NUM:0}
    password: ${REDIS_PASSWORD:}
    connect-timeout: ${REDIS_CONNECTION_TIMEOUT:PT10S}
    timeout: ${REDIS_READ_TIMEOUT:PT10S}
    client-type: lettuce
    lettuce:
      pool:
        max-active: ${REDIS_MAX_CONNECTION:4}

management:
  health:
    redis:
      enabled: ${ENABLE_REDIS_HEALTH_CHECK:true}
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  server:
    port: ${MANAGEMENT_SERVER_PORT:88}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}

custom:
  default-notification-ttl: ${DEFAULT_TTL_IN_SEC:6400}